Repository Central-MakeUs/dice-Front, pull requests merged in 2025-01, with the labels that each got.

#3 [DICE-1] 디자인 시스템 적용
  tailwind.config.js
Labels: Design

#8 [DICE-7] 아이폰 어플 로고 적용
  ios/dice.xcodeproj/project.pbxproj
  ios/dice/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/dice/Images.xcassets/AppIcon.appiconset/logo.png
  src/assets/logo.png
Labels: Chore

#20 [DICE - 13] 로그인 및 회원가입 페이지 구현
  AppInner.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/input/delete.svg
  src/assets/input/eye-off.svg
  src/assets/input/eye-on.svg
  src/assets/topNavigation/logo-black.svg
  src/assets/topNavigation/logo-white.svg
  src/assets/x.svg
  src/components/common/customButton.tsx
  src/components/topNavigation/topNavigation.tsx
  src/components/userInput/userInput.tsx
  src/screens/home/homeScreen.tsx
  src/screens/login/login.tsx
  src/screens/register/register.tsx
  src/type/stack/type.ts
Labels: Feat

#23 [DICE-22] CustomText 컴포넌트 제거에 따른 코드 전반 수정
  AppInner.tsx
  ios/Podfile.lock
  src/components/common/customButton.tsx
  src/screens/home/homeScreen.tsx
  src/screens/login/login.tsx
  src/screens/main/main.tsx
  src/screens/register/register.tsx
Labels: Fix, Chore

#26 Design: 로그인, 회원가입 페이지 delete 버튼 position: absolute 로 변경
  src/screens/login/login.tsx
  src/screens/register/register.tsx
Labels: Design

#28 [ DICE-27] 팝업공간 상세 스크린 뒤로가기 누락 추가
  src/assets/leftArrow.svg
  src/screens/popUpDetail/popUpDetail.tsx
Labels: Fix

#30 [DICE-29] 팝업공간 상세 스크린 지도 연결
  .gitignore
  babel.config.js
  env.d.ts
  ios/Config.xcconfig
  ios/Podfile.lock
  ios/Untitled.swift
  ios/dice.xcodeproj/project.pbxproj
  ios/dice.xcodeproj/xcshareddata/xcschemes/dice.xcscheme
  ios/dice/AppDelegate.mm
  ios/dice/Info.plist
  package-lock.json
  package.json
  src/assets/popUpDetail/downArrow.svg
  src/assets/popUpDetail/marker.svg
  src/screens/popUpDetail/dummyData.ts
  src/screens/popUpDetail/popUpDetail.tsx
  src/server/naverMap.ts
  src/utils/phoneCall.ts
  src/utils/website.ts
Labels: Feat, Chore

#40 [DICE-37] 찜목록 스크린 구현
  src/assets/blackLeftArrow.svg
  src/components/like/switch.tsx
  src/screens/like/dummyData.ts
  src/screens/like/like.tsx
Labels: Feat, Chore

#44 [DICE-43] 팝업 상세 스크린 배경색 일부 변경
  src/screens/popUpDetail/popUpDetail.tsx
Labels: Design

#56 [DICE-55] 필터링 모달 Open 메서드 누락
  src/screens/popUp/popUp.tsx
Labels: !HOTFIX
