Repository Central-MakeUs/dice-Front, pull requests merged in 2025-02, with the labels that each got.

#60 [DICE-57] 쪽지함 컴포넌트 수정
  src/components/chatBox/chatRoom.tsx
  src/components/common/customTwoBtnModal.tsx
  src/screens/chatBox/chatBox.tsx
  src/screens/chatBox/dummyData.ts
Labels: Feat, Fix

#59 [FEAT] recruitDetail 페이지 제작
  AppInner.tsx
  src/assets/recruit/like-empty.svg
  src/assets/recruit/like-full.svg
  src/components/common/chipContainer.tsx
  src/components/popUp/chipContainer.tsx
  src/components/recruit/recruitHeader.tsx
  src/components/recruit/recruitItem.tsx
  src/screens/popUp/popUp.tsx
  src/screens/recruit/recruit.tsx
  src/screens/recruit/recruitItemDummy.ts
  src/screens/recruitDetail/recruitDetail.tsx
  src/screens/recruitDetail/recruitDetailDummy.ts
  src/type/recruit/recruit.type.ts
  src/type/recruit/recruitDetail.type.ts
  src/type/stack/type.ts
Labels: Feat

#69 Fix: recruit 스크린의 cihpContainer 클릭 시 FilterContainer로 연결
  ios/Podfile.lock
  src/screens/popUp/popUp.tsx
  src/screens/recruit/recruit.tsx
Labels: Fix

#73 [DICE-72] API 연동
  app/(myPage)/_layout.tsx
  app/(myPage)/myBrand.tsx
  app/(myPage)/resetPassword.tsx
  app/(myPage)/updateInfo.tsx
  app/(tabs)/_layout.tsx
  app/(tabs)/announcement.tsx
  app/(tabs)/myPage.tsx
  app/(tabs)/reservation.tsx
  app/(tabs)/space.tsx
  app/_layout.tsx
  app/announcement/[id].tsx
  app/chatBox/index.tsx
  app/chatRoom/[id].tsx
  app/index.tsx
  app/like/index.tsx
  app/login/index.tsx
  app/space/[id].tsx
  components/announcement/announcementItem.tsx
  components/chatBox/chatRoom.tsx
  components/chatBox/header.tsx
  components/chatRoom/chat.tsx
  components/chatRoom/header.tsx
  components/common/filterContainer.tsx
  components/icon/icon.tsx
  components/like/switch.tsx
  components/popUp/card.tsx
  components/reservation/cardComponent.tsx
  components/topNavigation/topNavigation.tsx
  components/userInput/userInput.tsx
  constants/mocks/chatDummyData.ts
  hooks/announcement/announcement.ts
  hooks/auth/auth.ts
  hooks/guest/guest.ts
  hooks/like/like.ts
  hooks/space/space.ts
  package-lock.json
  package.json
  server/announcement/announcement.ts
  server/announcement/request.ts
  server/announcement/response.ts
  server/auth/auth.ts
  server/auth/request.ts
  server/auth/response.ts
  server/guest/guest.ts
  server/guest/response.ts
  server/like/like.ts
  server/like/response.ts
  server/space/response.ts
  server/space/space.ts
  types/announcement.ts
  types/page.ts
  utils/phoneCall.ts
  utils/time.ts
  zustands/filter/store.ts
Labels: Feat

#80 [DICE-76] ESLint 재적용
  .eslintrc.js
Labels: Chore

#89 [DICE-88] 필터링 (공간/공고) 값 수정
  app/(tabs)/space.tsx
  app/like/index.tsx
  app/reservation/reservation.tsx
  app/search/[type].tsx
  app/space/[id].tsx
  components/announcement/chipContainer.tsx
  components/announcement/filter/statusFilter.tsx
  components/announcement/filterContainer.tsx
  components/space/card.tsx
  components/space/chipContainer.tsx
  components/space/filter/header.tsx
  components/space/filter/peopleFilter.tsx
  components/space/filter/priceFilter.tsx
  components/space/filter/regionFilter.tsx
  components/space/filter/sortFilter.tsx
  components/space/filterContainer.tsx
  components/space/header.tsx
Labels: Fix, Chore

#91 [DICE-90] 게스트로 둘러보기 기능 추가
  app/(tabs)/announcement.tsx
  app/(tabs)/myPage.tsx
  app/(tabs)/space.tsx
  app/_layout.tsx
  app/announcement/[id].tsx
  app/index.tsx
  app/space/[id].tsx
  components/topNavigation/topNavigation.tsx
  hooks/auth/auth.ts
  hooks/autoLogin.ts
  zustands/member/store.ts
Labels: Feat, Fix
